/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Assignment = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
});
export const Attendance = IDL.Record({
  'present' : IDL.Bool,
  'date' : IDL.Text,
  'markedBy' : IDL.Principal,
  'student' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Material = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'file' : ExternalBlob,
  'fileType' : IDL.Text,
  'uploadTime' : Time,
  'uploadedBy' : IDL.Principal,
});
export const Subject = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'faculty' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllAttendanceRecords' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'getAllUniqueSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getAssignment' : IDL.Func([IDL.Text], [Assignment], ['query']),
  'getAssignmentsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getChatbotResponse' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMaterial' : IDL.Func([IDL.Text], [Material], ['query']),
  'getMaterialsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Material)],
      ['query'],
    ),
  'getSystemAnalytics' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssignment' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'uploadMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
  });
  const Attendance = IDL.Record({
    'present' : IDL.Bool,
    'date' : IDL.Text,
    'markedBy' : IDL.Principal,
    'student' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Material = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'file' : ExternalBlob,
    'fileType' : IDL.Text,
    'uploadTime' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const Subject = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'faculty' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllAttendanceRecords' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'getAllUniqueSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getAssignment' : IDL.Func([IDL.Text], [Assignment], ['query']),
    'getAssignmentsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getChatbotResponse' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMaterial' : IDL.Func([IDL.Text], [Material], ['query']),
    'getMaterialsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Material)],
        ['query'],
      ),
    'getSystemAnalytics' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssignment' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'uploadMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };