/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'title' : string,
  'subject' : string,
  'createdBy' : Principal,
  'description' : string,
  'deadline' : string,
}
export interface Attendance {
  'present' : boolean,
  'date' : string,
  'markedBy' : Principal,
  'student' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface Material {
  'title' : string,
  'subject' : string,
  'file' : ExternalBlob,
  'fileType' : string,
  'uploadTime' : Time,
  'uploadedBy' : Principal,
}
export type Subject = string;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'faculty' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createAssignment' : ActorMethod<[string, string, string, string], undefined>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllAttendanceRecords' : ActorMethod<[], Array<Attendance>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getAllUniqueSubjects' : ActorMethod<[], Array<Subject>>,
  'getAssignment' : ActorMethod<[string], Assignment>,
  'getAssignmentsBySubject' : ActorMethod<[string], Array<Assignment>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<Attendance>>,
  'getAttendanceByStudent' : ActorMethod<[Principal], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getChatbotResponse' : ActorMethod<[string], string>,
  'getMaterial' : ActorMethod<[string], Material>,
  'getMaterialsBySubject' : ActorMethod<[string], Array<Material>>,
  'getSystemAnalytics' : ActorMethod<[], [bigint, bigint, bigint, bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[Principal, string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAssignment' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'uploadMaterial' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];